routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){
Route::resource('companies', 'CompaniesController');
Route::get('projects/create/{company_id?}', 'ProjectsController@create');
Route::resource('projects', 'ProjectsController');
Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
Route::resource('roles', 'RolesController');
Route::get('tasks/create/{company_id? && project_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');
Route::resource('profile', 'ProfileController');
Route::post('profile', 'ProfileController@update_avatar')->name('profile.update_avatar');
Route::resource('password', 'PasswordController');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::resource('comments', 'CommentsController');
});

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable = [
        'name', 'description', 'company_id', 'user_id', 'days',
    ];

    /** A project belongs to a user */
    public function users(){
        return $this->belongsToMany('App\User');
    }

    /** A project belongs to a company  */
    public function company(){
        return $this->belongsTo('App\Company');
    }

    public function comments(){
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use App\User;
use App\ProjectUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = null;
        if (Auth::check()){
            $projects = Project::where('user_id', Auth::user()->id)->get();

            return view('projects.index', ['projects' => $projects]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id = null )
    {
        //
        $companies = null;
        if (!$company_id){
            $companies = Company::where('user_id', Auth::user()->id)->get();
        }
        return view('projects.create', ['company_id=>$company_id', 'companies'=>$companies]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $company_id = null;
        if (Auth::check()){
            $project = Project::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id,/** or $request->user()->id  */
                'days' => $request->input('days')
            ]);

            if($project){
                return redirect()->route('projects.show',['project' => $project->id])
                    ->with('success', 'Project Created Successfully');
            }
        }

        return back()->withInput()->with('errors','Error Creating New Project');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function show(Project $project)
    {
        //

        /**
         *  Or alternatively use this code to retrieve the project from the database
         */
        //$project = project::where('id', $project->id)->first();

        $project = Project::find($project->id);
        return view('projects.show', ['project'=> $project]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function edit(Project $project)
    {
        //
        $project = Project::find($project->id);
        return view('projects.edit', ['project'=> $project]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Project $project)
    {
        //Save data
        $projectUpdate = Project::where('id', $project->id)->update([
            'name' => $request->input('name'),
            'description' => $request->input('description')
        ]);

        if ($projectUpdate){
            return redirect()->route('projects.show', ['project'=>$project->id])
                ->with('success', 'project Updated successfully');
        }

        //Redirect to another page
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\project  $project
     * @return \Illuminate\Http\Response
     */
    public function destroy(Project $project)
    {
        //
        $findproject = Project::find($project->id);
        if($findproject->delete()){

            //redirect
            return redirect()->route('projects.index')
                ->with('success','Project Deleted Successfully');
        }

        return back()->withInput()->with('errors','project could not be Deleted');
    }

    /** Add user to projects method */
    public function adduser(Request $request){
        //add user to project(s)
        //Take a project, add a user to it
        $project = Project::find($request->input('project_id'));

        if (Auth::user()->id == $project->user_id){
        $project = Project::find($request->input('project_id'));
        $user = User::where('email', $request->input('email'))->first(); // we use first() while retrieving single record and get() while retrieving many records

            //Check if user is already added to the Project
            $projectUser = ProjectUser::where('user_id', $user->id)
                                      ->where('project_id', $project->id)
                                      ->first();

            if ($projectUser){
                // If user already exists, exit
                return redirect()->route('projects.show',['project' => $project->id])
                    ->with('info', 'User '.$request->input('email').' is already a member of this project');
            }

          if ($user && $project){
           $project->users()->attach($user->id);

              return redirect()->route('projects.show',['project' => $project->id])
                  ->with('success', 'User '.$request->input('email').' Added to Project Successfully');
          }
        }
        return redirect()->route('projects.show',['project' => $project->id])
            ->with('errors', 'Error Adding User '.$request->input('email').' to the Project');
    }

}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row">

            <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary" style="background-color: white;">

                <h1 class="text-center">CREATE PROJECT</h1>

                <form class="well form-horizontal" method="post" action="{{ route('projects.store') }}">
                    {{ csrf_field() }}

                    <!--input type="hidden" name="_method" value="put"-->

                    <div class="form-group">
                        <label class="control-label" for="project-name">Name <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-list-alt" aria-hidden="true"></i></span>
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   id="project-name"
                                   spellcheck="fslse"
                                   placeholder="Enter Project Name"
                                   required>
                        </div>
                    </div>

                        @if($companies == null)
                            <input
                                    class="form-control"
                                    type="hidden"
                                    name="company_id"
                                    value="{{-- $company_id --}}"
                            />
                        @endif


                    @if($companies != null)
                    <div class="form-group">
                        <label class="control-label" for="company-content">Select Company <span class="required">*</span> </label>
                        <div class="input-group">
                             <span class="input-group-addon"> <i class="fa fa-compass" aria-hidden="true"></i></span>
                             <select class="form-control" name="company_id">
                                 @foreach($companies as $company)
                                 <option value="{{$company->id}}">{{ $company->name }}</option>
                                 @endforeach
                             </select>
                        </div>
                    </div>
                    @endif


                    <div class="form-group">
                        <label class="control-label" for="project-content">Description</label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                            <textarea style="resize: vertical;"
                                      class="form-control autosize-target text-left"
                                      name="description"
                                      id="project-content"
                                      rows="5" spellcheck="false"
                                      placeholder="Enter Project Description"
                                      required>
                            </textarea>
                        </div>
                    </div>

                    <div class="form-group">
                         <label class="control-label" for="project-name">Days <span class="required">*</span> </label>
                         <div class="input-group">
                             <span class="input-group-addon"> <i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
                             <input type="text"
                                     class="form-control"
                                     name="days"
                                     id="days"
                                     spellcheck="false"
                                     placeholder="Enter Number of Days e.g. 10"
                                     required>
                         </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="create" name="create"><strong>Create Project </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                    </div>

                </form>

            </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/projects"><i class="fa fa-th-list" aria-hidden="true"></i> My Projects</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="wrapper">
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row" style="margin: 10px;">

            <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary" style="background-color: white;">

                <h1 class="text-center">UPDATE PROJECT</h1>

                <form class="well form-horizontal" method="post" action="{{ route('companies.update', [$project->id]) }}">
                    {{ csrf_field() }}

                    <input type="hidden" name="_method" value="put">

                    <div class="form-group">
                        <label class="control-label" for="company-name">Name <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-sitemap" aria-hidden="true"></i></span>
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   id="company-name"
                                   spellcheck="false"
                                   placeholder="Enter Company Name"
                                   required
                                   value="{{ $project->name }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="company-content">Description</label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                            <textarea style="resize: vertical;"
                                      class="form-control autosize-target text-left"
                                      name="description"
                                      id="company-content"
                                      rows="5" spellcheck="false"
                                      placeholder="Enter Company Description"
                                      required
                            >{{ $project->description }}
                                </textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="update" name="update"><strong>Update Project </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                    </div>

                </form>

            </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/projects"><i class="fa fa-th-list" aria-hidden="true"></i> All Projects</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Projects <a class="pull-right btn btn-primary btn-sm" href="/projects/create">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Project</a> </div>
            <div class="panel-body">
                <ul class="list-group">
                    @foreach($projects as $project)
                        <li class="list-group-item">
                            <i class="fa fa-play" aria-hidden="true"></i> <a href="/projects/{{ $project->id }}" > {{ $project->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/projects/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-sm-9 col-md-9 col-lg-9 pull-left show">

    <!-- Jumbotron -->
    <div class=" panel panel-primary well well-lg">
        <h1>{{ $project->name }}</h1>
        <p class="lead">{{ $project->description }}</p>
        <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
    </div>

    <!-- Example row of columns -->
    <div class="row comment" style="margin: 3px;">

    @include('partials.comments')

        <!--<li class="btn btn-default btn-sm pull-right"><a href="/projects/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Project</a></li>-->

        {{--@foreach($project->projects as $project)
        <div class="col-lg-4">
            <h2>{{ $project->name }}</h2>

            <p class="text-danger"> {{ $project->description }} </p>
            <p><a class="btn btn-primary" href="/projects/{{ $project->id  }}" role="button">View Project <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a></p>
        </div>
        @endforeach --}}

        <form class="well form-horizontal comment" method="post" action="{{ route('comments.store') }}">
        {{ csrf_field() }}

                    <input type="hidden" name="commentable_type" value="App\Project">

                    <input type="hidden" name="commentable_id" value="{{ $project->id }}">

            <div class="text-center"><i class="fa fa-comments" aria-hidden="true"></i> COMMENTS</div>

            <div class="form-group">
                <label class="control-label" for="comment-content">Comment</label>
                <div class="input-group">
                    <span class="input-group-addon"> <i class="fa fa-commenting" aria-hidden="true"></i></span>
                    <textarea style="resize: vertical;"
                              class="form-control autosize-target text-left"
                              name="body"
                              id="comment-content"
                              rows="3" spellcheck="fslse"
                              placeholder="Enter Comment"
                              required>
                            </textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label" for="company-content">Proof of Work Done(Url/Photos)</label>
                <div class="input-group">
                    <span class="input-group-addon"> <i class="fa fa-link" aria-hidden="true"></i></span>
                    <textarea style="resize: vertical;"
                              class="form-control autosize-target text-left"
                              name="url"
                              id="comment-content"
                              rows="2" spellcheck="fslse"
                              placeholder="Enter Url of Screenshots"
                              required>
                            </textarea>
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="create" name="create"><strong>Comment </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
            </div>

        </form>
        <div class="clearfix"></div>

    </div>

            </div>
        </div>
    </div>

</div>

<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
    <div class="sidebar-module sidebar-module-inset">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
        <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
    </div>
    <hr>

    <div class="sidebar-module">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
        <ol class="list-unstyled" style="padding-top: 4px; margin: 10px auto;">
            <li><a href="/projects/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Project</a></li>
            <li><a href="/projects/{{ $project->id }}/edit"><i class="fa fa-pencil-square" aria-hidden="true"></i> Edit</a></li>
            <li><a href="/projects"><i class="fa fa-eye" aria-hidden="true"></i> View List of Projects</a></li>

            @if($project->user_id == Auth::user()->id)
            <li>
                <a href="#"
                    onclick="
                     var result = confirm('Are you sure you want to delete this project?');
                       if(result){
                       event.preventDefault();
                       document.getElementById('delete-form').submit();
                       }
                        "><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                <form id="delete-form" action="{{ route('projects.destroy', [$project->id]) }}"
                      method="post" style="display: none;">
                    <input type="hidden" name="_method" value="delete">
                    {{ csrf_field() }}
                </form>
            </li>
            @endif
            <li><a href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New Member</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href="#">March 2014</a></li>
        </ol>
    </div>
    -->

    <div class="sidebar-module">
        <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
        <ol class="list-unstyled">
            <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                     GitHub</a></li>
            <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                    Twitter</a></li>
            <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                     Facebook</a></li>
        </ol>
        <hr>

        <h4><i class="fa fa-plus" aria-hidden="true"></i> Add Members</h4>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <form class="well form-horizontal" method="post" action="{{ route('projects.adduser') }}"> <!-- or just use projects/adduser instead of the route -->
                    {{ csrf_field() }}
                <div class="input-group">
                    <input name="project_id" type="hidden" class="form-control" value="{{ $project->id }}">
                    <input name="email" type="text" class="form-control" placeholder="Enter Email">
                    <span class="input-group-btn">
        <button class="btn btn-success" type="submit">Add Members <i class="fa fa-plus-square" aria-hidden="true"></i></button>
      </span>
                </div><!-- /input-group -->
                </form>
            </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->

        <h4><i class="fa fa-users" aria-hidden="true"></i> Team Members</h4>
        <ol class="list-unstyled" style="padding-top: 4px; margin: 10px auto;">
            @foreach($project->users as $user)
            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> {{ $user->first_name }} {{ $user->middle_name }}</a></li>
            @endforeach
        </ol>

    </div>
</div>

@endsection