routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){
Route::resource('companies', 'CompaniesController');
Route::get('projects/create/{company_id?}', 'ProjectsController@create');
Route::resource('projects', 'ProjectsController');
Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
Route::resource('roles', 'RolesController');
Route::get('tasks/create/{company_id? && project_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');
Route::resource('profile', 'ProfileController');
Route::post('profile', 'ProfileController@update_avatar')->name('profile.update_avatar');
Route::resource('password', 'PasswordController');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::resource('comments', 'CommentsController');
});

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    //
    protected $fillable = [
        'name', 'description', 'user_id',
    ];

    /** A company belongs to a user */
    public function user(){
        return $this->belongsTo('App\User');
    }

    public function projects(){
        return $this->hasMany('App\Project');
    }

    /** Every company has many comments */
    public function comments(){
        return $this->morphMany('App\Comment', 'commentable');
    }

}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use App\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (Auth::check()){
        $companies = Company::where('user_id', Auth::user()->id)->get();

        return view('companies.index', ['companies' => $companies]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if (Auth::check()){
            $company = Company::create([
               'name' => $request->input('name'),
                'description' => $request->input('description'),
                'user_id' => Auth::user()->id /** or $request->user()->id  */
            ]);

            if($company){
                return redirect()->route('companies.show',['company' => $company->id])
                    ->with('success', 'Company Created Successfully');
            }
        }

        return back()->withInput()->with('errors','Error Creating New Company');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //

        /**
         *  Or alternatively use this code to retrieve the company from the database
         */
        //$company = Company::where('id', $company->id)->first();

        $company = Company::find($company->id);
        return view('companies.show', ['company'=> $company]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //
        $company = Company::find($company->id);
        return view('companies.edit', ['company'=> $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Company $company)
    {
        //Save data
        $companyUpdate = Company::where('id', $company->id)->update([
            'name' => $request->input('name'),
            'description' => $request->input('description')
        ]);

        if ($companyUpdate){
            return redirect()->route('companies.show', ['company'=>$company->id])
                ->with('success', 'Company Updated successfully');
        }

        //Redirect to another page
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        //
        $findCompany = Company::find($company->id);
        if($findCompany->delete()){

            //redirect
            return redirect()->route('companies.index')
                ->with('success','Company Deleted Successfully');
        }

        return back()->withInput()->with('errors','Company could not be Deleted');
    }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row">

            <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary"  style="background-color: white;">

                <h1 class="text-center">CREATE NEW COMPANY</h1>

                <form class="well form-horizontal" method="post" action="{{ route('companies.store') }}">
                    {{ csrf_field() }}

                    <!--input type="hidden" name="_method" value="put"-->

                    <div class="form-group">
                        <label class="control-label" for="company-name">Name <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-building" aria-hidden="true"></i> </span>
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   id="company-name"
                                   spellcheck="false"
                                   placeholder="Enter Company Name"
                                   required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="company-content">Description</label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                            <textarea style="resize: vertical;"
                                      class="form-control autosize-target text-left"
                                      name="description"
                                      id="company-content"
                                      rows="5" spellcheck="false"
                                      placeholder="Enter Company Description"
                                      required>
                            </textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="create" name="create"><strong>Create Company </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                    </div>

                </form>

            </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/companies"><i class="fa fa-th-list" aria-hidden="true"></i> My Companies</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="wrapper">
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row" style="margin: 10px;">

                <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary" style="background-color: white;">

                    <h1 class="text-center">UPDATE COMPANY</h1>

                    <form class="well form-horizontal" method="post" action="{{ route('companies.update', [$company->id]) }}">
                        {{ csrf_field() }}

                        <input type="hidden" name="_method" value="put">

                        <div class="form-group">
                            <label class="control-label" for="company-name">Name <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-sitemap" aria-hidden="true"></i></span>
                                <input type="text"
                                       class="form-control"
                                       name="name"
                                       id="company-name"
                                       spellcheck="fslse"
                                       placeholder="Enter Company Name"
                                       required
                                       value="{{ $company->name }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="company-content">Description</label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                                <textarea style="resize: vertical;"
                                       class="form-control autosize-target text-left"
                                       name="description"
                                       id="company-content"
                                       rows="5" spellcheck="false"
                                       placeholder="Enter Company Description"
                                       required
                                       >{{ $company->description }}
                                </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="update" name="update"><strong>Update Company </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                        </div>

                    </form>

                </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/companies"><i class="fa fa-th-list" aria-hidden="true"></i> All Companies</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
    </div>
@endsection

resources/views/companies/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Companies <a class="pull-right btn btn-primary btn-sm" href="companies/create">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Company</a> </div>
            <div class="panel-body">
                <ul class="list-group">
                    @foreach($companies as $company)
                        <li class="list-group-item">
                            <i class="fa fa-play" aria-hidden="true"></i> <a href="/companies/{{ $company->id }}" > {{ $company->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-sm-9 col-md-9 col-lg-9 pull-left">

    <!-- Jumbotron -->
    <div class="jumbotron">
        <h1>{{ $company->name }}</h1>
        <p class="lead">{{ $company->description }}</p>
        <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
    </div>

    <!-- Example row of columns -->
    <div class="row" style="background-color: white; margin: 10px;">

        <li class="btn btn-default btn-sm pull-right"><a href="/projects/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Project</a></li>

        @foreach($company->projects as $project)
        <div class="col-lg-4">
            <h2>{{ $project->name }}</h2>

            <p class="text-danger"> {{ $project->description }} </p>
            <p><a class="btn btn-primary" href="/projects/{{ $project->id  }}" role="button">View Project <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a></p>
        </div>
        @endforeach
    </div>

</div>

<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
    <div class="sidebar-module sidebar-module-inset">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
        <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
    </div>
    <hr>

    <div class="sidebar-module">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
        <ol class="list-unstyled" style="padding-top: 4px; margin: 10px auto;">
            <li><a href="/companies/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Company</a></li>
            <li><a href="/companies/{{ $company->id }}/edit"><i class="fa fa-pencil-square" aria-hidden="true"></i> Edit</a></li>
            <li><a href="/companies"><i class="fa fa-eye" aria-hidden="true"></i> View List of Companies</a></li>
            <li><a href="/projects/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Project</a></li>
            <li>
                <a href="#"
                    onclick="
                     var result = confirm('Are you sure you want to delete this project?');
                       if(result){
                       event.preventDefault();
                       document.getElementById('delete-form').submit();
                       }
                        "><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                <form id="delete-form" action="{{ route('companies.destroy', [$company->id]) }}"
                      method="post" style="display: none;">
                    <input type="hidden" name="_method" value="delete">
                    {{ csrf_field() }}
                </form>
            </li>
            <li><a href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New Member</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href="#">March 2014</a></li>
        </ol>
    </div>
    -->

    <div class="sidebar-module">
        <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
        <ol class="list-unstyled">
            <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                     GitHub</a></li>
            <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                    Twitter</a></li>
            <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                     Facebook</a></li>
        </ol>
    </div>
</div>
@endsection