routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function (){
Route::resource('companies', 'CompaniesController');
Route::get('projects/create/{company_id?}', 'ProjectsController@create');
Route::resource('projects', 'ProjectsController');
Route::post('projects/adduser', 'ProjectsController@adduser')->name('projects.adduser');
Route::resource('roles', 'RolesController');
Route::get('tasks/create/{company_id? && project_id?}', 'TasksController@create');
Route::resource('tasks', 'TasksController');
Route::post('tasks/adduser', 'TasksController@adduser')->name('tasks.adduser');
Route::resource('profile', 'ProfileController');
Route::post('profile', 'ProfileController@update_avatar')->name('profile.update_avatar');
Route::resource('password', 'PasswordController');
Route::post('/changePassword', 'HomeController@changePassword')->name('changePassword');
Route::resource('comments', 'CommentsController');
});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
    protected $fillable = [
        'name', 'description', 'project_id', 'user_id', 'company_id', 'days', 'hours',
    ];

    /** Every task belongs to a user */
    public function user(){
        return $this->belongsTo('App\User');
    }

    /** Every task belongs to a user */
    public function project(){
        return $this->belongsTo('App\Project');
    }

    /** Every task belongs to a user */
    public function company(){
        return $this->belongsTo('App\Company');
    }

    /** A task belongs to many user */
    public function users(){
        return $this->belongsToMany('App\User');
    }

    /** Every Task has many comments */
    public function comments(){
        return $this->morphMany('App\Comment', 'commentable');
    }
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use App\Project;
use App\Company;
use App\Task;
use App\User;
use App\TaskUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = null;
        $projects = null;
        if (Auth::check()){
            $tasks = Task::where('user_id', Auth::user()->id)->get();

            return view('tasks.index', ['tasks' => $tasks]);
        }
        return view('auth.login');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create( $company_id = null,$project_id = null )
    {
        //
        if (!$company_id && !$project_id){
            $companies = Company::where('user_id', Auth::user()->id)->get();
            $projects = Project::where('user_id', Auth::user()->id)->get();
            //$tasks = Task::where('user_id', Auth::user()->id)->get();
        }
        return view('tasks.create', ['company_id=>$company_id', 'companies'=>$companies], ['project_id=>$project_id', 'projects'=>$projects]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        if (Auth::check()){
            $task = Task::create([
                'name' => $request->input('name'),
                'description' => $request->input('description'),
                'project_id' => $request->input('project_id'),
                'company_id' => $request->input('company_id'),
                'user_id' => Auth::user()->id,/** or $request->user()->id  */
                'days' => $request->input('days'),
                'hours' => $request->input('hours')
            ]);

            if($task){
                return redirect()->route('tasks.show',['task' => $task->id])
                    ->with('success', 'Task Created Successfully');
            }
        }

        return back()->withInput()->with('errors','Error Creating New Task');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Task  $Task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        //

        /**
         *  Or alternatively use this code to retrieve the Task from the database
         */
        //$task = Task::where('id', $task->id)->first();

        $task = Task::find($task->id);
        return view('tasks.show', ['task'=> $task]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Task  $Task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
        $task = Task::find($task->id);
        return view('tasks.edit', ['task'=> $task]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Task  $Task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //Save data
        $taskUpdate = Task::where('id', $task->id)->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'days' => $request->input('days'),
            'hours' => $request->input('hours')
        ]);

        if ($taskUpdate){
            return redirect()->route('tasks.show', ['task'=>$task->id])
                ->with('success', 'Task Updated Successfully');
        }

        //Redirect to another page
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Task  $Task
     * @return \Illuminate\Http\Response
     */
    public function destroy(Task $task)
    {
        //
        $findtask = Task::find($task->id);
        if($findtask->delete()){

            //redirect
            return redirect()->route('tasks.index')
                ->with('success','Task Deleted Successfully');
        }

        return back()->withInput()->with('errors','Task could not be Deleted');
    }

    /** Add user to Tasks method */
    public function adduser(Request $request){
        //add user to Task(s)
        //Take a Task, add a user to it
        $task = Task::find($request->input('task_id'));

        if (Auth::user()->id == $task->user_id){
            $task = Task::find($request->input('task_id'));
            $user = User::where('email', $request->input('email'))->first(); // we use first() while retrieving single record and get() while retrieving many records

            //Check if user is already added to the Task
            $taskUser = TaskUser::where('user_id', $user->id)
                ->where('task_id', $task->id)
                ->first();

            if ($taskUser){
                // If user already exists, exit
                return redirect()->route('tasks.show',['task' => $task->id])
                    ->with('info', 'User '.$request->input('email').' is already a member of this Task');
            }

            if ($user && $task){
                $task->users()->attach($user->id);

                return redirect()->route('tasks.show',['task' => $task->id])
                    ->with('success', 'User '.$request->input('email').' Added to Task Successfully');
            }
        }
        return redirect()->route('tasks.show',['task' => $task->id])
            ->with('errors', 'Error Adding User '.$request->input('email').' to the Task');
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row">

            <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary" style="background-color: white;">

                <h1 class="text-center">CREATE TASKS</h1>

                <form class="well form-horizontal" method="post" action="{{ route('tasks.store') }}">
                {{ csrf_field() }}

                <!--input type="hidden" name="_method" value="put"-->

                    <div class="form-group">
                        <label class="control-label" for="task-name">Name <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-list-alt" aria-hidden="true"></i></span>
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   id="project-name"
                                   spellcheck="fslse"
                                   placeholder="Enter Task Name"
                                   required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="project-content">Description</label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                            <textarea style="resize: vertical;"
                                      class="form-control autosize-target text-left"
                                      name="description"
                                      id="task-content"
                                      rows="1" spellcheck="false"
                                      placeholder="Enter Task Description"
                                      required>
                            </textarea>
                        </div>
                    </div>

                    @if($companies == null)
                        <input
                                class="form-control"
                                type="hidden"
                                name="company_id"
                                value="{{ $company_id }}"
                        />
                    @endif

                    @if($projects == null)
                        <input
                                class="form-control"
                                type="hidden"
                                name="project_id"
                                value="{{ $project_id }}"
                        />
                    @endif


                    @if($companies != null)
                        <div class="form-group">
                            <label class="control-label" for="company-content">Select Company <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-compass" aria-hidden="true"></i></span>
                                <select class="form-control" name="company_id">
                                    @foreach($companies as $company)
                                        <option value="{{$company->id}}">{{ $company->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    @endif


                    @if($projects != null)
                        <div class="form-group">
                            <label class="control-label" for="project-content">Select Project <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-compass" aria-hidden="true"></i></span>
                                <select class="form-control" name="project_id">
                                    @foreach($projects as $project)
                                        <option value="{{$project->id}}">{{ $project->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    @endif

                    <div class="form-group">
                        <label class="control-label" for="task-name">Days <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
                            <input type="text"
                                   class="form-control"
                                   name="days"
                                   id="days"
                                   spellcheck="false"
                                   placeholder="Enter Number of Days e.g. 10"
                                   required>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label" for="task-name">Hours <span class="required">*</span> </label>
                        <div class="input-group">
                            <span class="input-group-addon"> <i class="fa fa-clock-o" aria-hidden="true"></i></span>
                            <input type="text"
                                   class="form-control"
                                   name="hours"
                                   id="hours"
                                   spellcheck="false"
                                   placeholder="Enter Number of Hours e.g. 4"
                                   required>
                        </div>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-primary" type="create" name="create"><strong>Create Task </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                    </div>

                </form>

            </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>
        <hr>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/tasks"><i class="fa fa-th-list" aria-hidden="true"></i> My Tasks</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-sm-9 col-md-9 col-lg-9 pull-left">

        <!-- Example row of columns -->
        <div class="row">

            <div class="col-sm-9 col-md-9 col-lg-9 col-lg-offset-2 col-md-offset-2 col-sm-offset-2 panel panel-primary" style="background-color: white;">

                    <h1 class="text-center">UPDATE TASK</h1>

                    <form class="well form-horizontal" method="post" action="{{ route('tasks.update', [$task->id]) }}">
                        {{ csrf_field() }}

                        <input type="hidden" name="_method" value="put">

                        <div class="form-group">
                            <label class="control-label" for="company-name">Name <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-sitemap" aria-hidden="true"></i></span>
                                <input type="text"
                                       class="form-control"
                                       name="name"
                                       id="task-name"
                                       spellcheck="false"
                                       placeholder="Enter Task Name"
                                       required
                                       value="{{ $task->name }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="project-content">Description</label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-keyboard-o" aria-hidden="true"></i> </span>
                                <textarea style="resize: vertical;"
                                          class="form-control autosize-target text-left"
                                          name="description"
                                          id="task-content"
                                          rows="1" spellcheck="false"
                                          placeholder="Enter Task Description"
                                          required>{{ $task->description }}
                            </textarea>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="task-name">Days <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
                                <input type="text"
                                       class="form-control"
                                       name="days"
                                       id="days"
                                       spellcheck="false"
                                       placeholder="Enter Number of Days e.g. 10"
                                       required
                                       value="{{ $task->days }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label" for="task-name">Hours <span class="required">*</span> </label>
                            <div class="input-group">
                                <span class="input-group-addon"> <i class="fa fa-calendar-plus-o" aria-hidden="true"></i></span>
                                <input type="text"
                                       class="form-control"
                                       name="hours"
                                       id="hours"
                                       spellcheck="false"
                                       placeholder="Enter Number of Hours e.g. 4"
                                       required
                                       value="{{ $task->hours }}">
                            </div>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-primary" type="update" name="update"><strong>Update Task </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
                        </div>

                    </form>

                </div>

        </div>

    </div>

    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
        <div class="sidebar-module sidebar-module-inset">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
            <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
        </div>
        <hr>

        <div class="sidebar-module">
            <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
            <ol class="list-unstyled">
                <li class="btn btn-default"><a href="/tasks"><i class="fa fa-th-list" aria-hidden="true"></i> All Tasks</a></li>
            </ol>
        </div>

        <!--
        <div class="sidebar-module">
            <h4>Members</h4>
            <ol class="list-unstyled">
                <li><a href="#">March 2014</a></li>
            </ol>
        </div>
        -->

        <div class="sidebar-module">
            <h4>Social Links</h4>
            <ol class="list-unstyled">
                <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                        GitHub</a></li>
                <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                        Twitter</a></li>
                <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                        Facebook</a></li>
            </ol>
        </div>
    </div>
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Tasks <a class="pull-right btn btn-primary btn-sm" href="/tasks/create">
                    <i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Task</a> </div>
            <div class="panel-body">
                <ul class="list-group">
                    @foreach($tasks as $task)
                        <li class="list-group-item">
                            <i class="fa fa-play" aria-hidden="true"></i> <a href="/tasks/{{ $task->id }}" > {{ $task->name }}</a></li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('content')
<div class="col-sm-9 col-md-9 col-lg-9 pull-left show">

    <!-- Jumbotron -->
    <div class=" panel panel-primary well well-lg">
        <h1>{{ $task->name }}</h1>
        <p class="lead">{{ $task->description }}</p>
        <!-- <p><a class="btn btn-lg btn-success" href="#" role="button">Get started today</a></p> -->
    </div>

    <!-- Example row of columns -->
    <div class="row comment" style="margin: 3px;">

    @include('partials.commentstasks')

        <!--<li class="btn btn-default btn-sm pull-right"><a href="/projects/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add Project</a></li>-->

        {{--@foreach($project->projects as $project)
        <div class="col-lg-4">
            <h2>{{ $project->name }}</h2>

            <p class="text-danger"> {{ $project->description }} </p>
            <p><a class="btn btn-primary" href="/projects/{{ $project->id  }}" role="button">View Project <i class="fa fa-chevron-circle-right" aria-hidden="true"></i>
                </a></p>
        </div>
        @endforeach --}}

        <form class="well form-horizontal comment" method="post" action="{{ route('comments.store') }}">
        {{ csrf_field() }}

                    <input type="hidden" name="commentable_type" value="App\Task">

                    <input type="hidden" name="commentable_id" value="{{ $task->id }}">

            <div class="text-center"><i class="fa fa-comments" aria-hidden="true"></i> COMMENTS</div>

            <div class="form-group">
                <label class="control-label" for="comment-content">Comment</label>
                <div class="input-group">
                    <span class="input-group-addon"> <i class="fa fa-commenting" aria-hidden="true"></i></span>
                    <textarea style="resize: vertical;"
                              class="form-control autosize-target text-left"
                              name="body"
                              id="comment-content"
                              rows="3" spellcheck="false"
                              placeholder="Enter Comment"
                              required>
                            </textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label" for="company-content">Proof of Work Done(Url/Photos)</label>
                <div class="input-group">
                    <span class="input-group-addon"> <i class="fa fa-link" aria-hidden="true"></i></span>
                    <textarea style="resize: vertical;"
                              class="form-control autosize-target text-left"
                              name="url"
                              id="comment-content"
                              rows="2" spellcheck="false"
                              placeholder="Enter Url of Screenshots"
                              required>
                            </textarea>
                </div>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="create" name="create"><strong>Comment </strong> <span><i class="fa fa-paper-plane" aria-hidden="true"></i></span></button>
            </div>

        </form>
        <div class="clearfix"></div>

    </div>

            </div>
        </div>
    </div>

</div>

<div class="col-sm-3 col-md-3 col-lg-3 pull-right">
    <div class="sidebar-module sidebar-module-inset">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> About</h4>
        <p>Pmanager <em>is a project management tool</em> that enables people manage projects and tasks more conviniently and efficiently.</p>
    </div>
    <hr>

    <div class="sidebar-module">
        <h4><i class="fa fa-chevron-circle-down" aria-hidden="true"></i> Actions Manager</h4>
        <ol class="list-unstyled" style="padding-top: 4px; margin: 10px auto;">
            <li><a href="/tasks/create"><i class="fa fa-plus-circle" aria-hidden="true"></i> Create New Task</a></li>
            <li><a href="/tasks/{{ $task->id }}/edit"><i class="fa fa-pencil-square" aria-hidden="true"></i> Edit</a></li>
            <li><a href="/tasks"><i class="fa fa-eye" aria-hidden="true"></i> View List of Tasks</a></li>

            @if($task->user_id == Auth::user()->id)
            <li>
                <a href="#"
                    onclick="
                     var result = confirm('Are you sure you want to delete this task?');
                       if(result){
                       event.preventDefault();
                       document.getElementById('delete-form').submit();
                       }
                        "><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
                <form id="delete-form" action="{{ route('tasks.destroy', [$task->id]) }}"
                      method="post" style="display: none;">
                    <input type="hidden" name="_method" value="delete">
                    {{ csrf_field() }}
                </form>
            </li>
            @endif
            <li><a href="#"><i class="fa fa-plus-circle" aria-hidden="true"></i> Add New Member</a></li>
        </ol>
    </div>

    <!--
    <div class="sidebar-module">
        <h4>Members</h4>
        <ol class="list-unstyled">
            <li><a href="#">March 2014</a></li>
        </ol>
    </div>
    -->

    <div class="sidebar-module">
        <h4><i class="fa fa-connectdevelop" aria-hidden="true"></i> Social Links</h4>
        <ol class="list-unstyled">
            <li><a href="#"><i class="fa fa-github" aria-hidden="true"></i>
                     GitHub</a></li>
            <li><a href="#"><i class="fa fa-twitter-square" aria-hidden="true"></i>
                    Twitter</a></li>
            <li><a href="#"><i class="fa fa-facebook-square" aria-hidden="true"></i>
                     Facebook</a></li>
        </ol>
        <hr>

        <h4><i class="fa fa-plus" aria-hidden="true"></i> Add Members</h4>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <form class="well form-horizontal" method="post" action="{{ route('tasks.adduser') }}"> <!-- or just use projects/adduser instead of the route -->
                    {{ csrf_field() }}
                <div class="input-group">
                    <input name="task_id" type="hidden" class="form-control" value="{{ $task->id }}">
                    <input name="email" type="text" class="form-control" placeholder="Enter Email">
                    <span class="input-group-btn">
        <button class="btn btn-success" type="submit">Add Members <i class="fa fa-plus-square" aria-hidden="true"></i></button>
      </span>
                </div><!-- /input-group -->
                </form>
            </div><!-- /.col-lg-6 -->
        </div><!-- /.row -->

        <h4><i class="fa fa-users" aria-hidden="true"></i> Team Members</h4>
        <ol class="list-unstyled" style="padding-top: 4px; margin: 10px auto;">
            @foreach($task->users as $user)
            <li><a href="#"><i class="fa fa-user" aria-hidden="true"></i> {{ $user->first_name }} {{ $user->middle_name }}</a></li>
            @endforeach
        </ol>

    </div>
</div>

@endsection